[package]
name = "use_cases"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.86"
chrono = "0.4.39"
chrono-tz = "0.10.3"
entities = { path = "../entities" }
futures = "0.3.31"
thiserror = "2.0.11"
tokio = "1.44.2"
tracing = "0.1.41"
uuid = "1.13.1"
